spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test_database
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:10001/test_database
#    username: test_user
#    password: test_password
server:
  port: 8800

application:
  security:
    jwt:
      issuer: ZornX5
      secret-key: 404E635266556A586E327235753T782F413F4428472B4B6250645367566B5970
      expiration: 5
      refresh-token:
        expiration: 30

logging:
  level:
    io.github.zornx5: debug
